### ISSUE TITLE
Where are the benchmarks and a runner?

### ISSUE THREAD

**Issue by mattip** [DuToitSpies/msc_cython_benchmarks#1]
I want to try to replicate this work for PyPy, is the code public?

**Comment by DuToitSpies** [comment]
Thanks for reminding me that I hadn't actually uploaded them yet! I've added the benchmarks and the runners now.

**Comment by mattip** [comment]
Thanks. Do you know if the talk at [pyconza 2024](https://za.pycon.org/talks/38-implementing-an-hpy-backend-for-cython/) was recorded?

**Comment by DuToitSpies** [comment]
I managed to find it on Youtube (https://www.youtube.com/watch?v=_RRhB14Qxo0&t=1631s) - it doesn't seem like any other talks have been uploaded yet, so it might just be there due to an oversight
